name: clip-time-series
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyproj # Always include to avoid PROJ conflicts
  - toml
  - nox
  - rasterio
  - gdal=3.8.3
  - geopandas=1.0.1
  - natsort
  - pypdf=5.0.1
  - wand=0.6.7
  - unidecode
  - pip
  - scikit-image=0.24.0
  - pip:
      - sepal_ui==2.21.0
      - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#egg=earthengine-api&subdirectory=python
